# Neon (readability-fixed)
# https://xcolors.net/neon

foreground=#f8f8f8
background=#171717

color0=#2D2D2D
color8=#888888

color1=#ED2E7B
color9=#FF0505

color2=#97d01a
color10=#76b639

color3=#ffa800
color11=#e1a126

color4=#16b1fb
color12=#289cd5

color5=#ff2491
color13=#ff2491

color6=#0fdcb6
color14=#0a9b81

color7=#ebebeb
color15=#f8f8f8
