# remap prefix to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g history-limit 100000
set -g base-index 1

set -g set-titles on
set -g set-titles-string "tmux@#H: #S #W"

set -g status-position top
set -g status-style "bg=black,fg=white"

set -g status-left "#{@shell_status} "
set -g status-left-length 200

set -g status-right " #S@#H "

set -g window-status-current-style "bold"
