# remap prefix to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g history-limit 100000
set -g base-index 1

set -g set-titles on
set -g set-titles-string "tmux@#H: #S #W"

set -g status-position top
